### ISSUE TITLE
Make requirements.txt more permissive

### ISSUE THREAD

**Issue by slazicoicr** [bow/crimson#10]
Current, the PyYAML version is fixed to 5.2.
https://github.com/bow/crimson/blob/4598afe9e0708cd9eea674e7168c7c59ef77bb3a/requirements.txt#L2

PyYAML 5.3 has been released, so I am getting `ERROR: crimson 0.5.0 has requirement PyYAML==5.2, but you'll have pyyaml 5.3 which is incompatible.` as other packages probably have more permissive requirements (PyYAML>=5.1).

Can `crimson` move to 5.3 or allow a more permissive requirement?

**Comment by bow** [comment]
Thanks for opening an issue @slazicoicr. [Crimson v0.5.1 was just released on PyPI](https://pypi.org/project/crimson/) with more relaxed requirements. This should solve your issue :).
