### ISSUE TITLE
Reading a picard file created on linux fails on Windows OS

### ISSUE THREAD

**Issue by myourshaw** [bow/crimson#15]
Crimson is an excellent app that has saved me many weary hours.

Recently I ran into a problem running Crimson on a Windows computer--

When opening a picard file, crimson looks for line separators equal to the current system value (os.linesep). This is "\r\n" on Windows. This causes a failure when a picard file produced on linux ("\n" separator) is read on a windows computer.

**Comment by bow** [comment]
@myourshaw Thanks for reporting this and glad to hear that :). I'll see if I can expose the line separator as an optional value that can be overridden, defaulting to `os.linesep` still.

**Comment by bow** [comment]
@myourshaw I've just pushed an [alpha release to PyPI](https://pypi.org/project/crimson/1.0.0a1/) which is installable via `pip`. I realized some cleanups and re-setup of the package is required (hence the alpha marker), but I hope this is already usable for you for the time being.

I'll keep this open for another week or so ~ unless of course there are additional comments / suggestions. Thanks again!

**Comment by bow** [comment]
Closing this issue since 1.0.0 is now out :slightly_smiling_face: in [PyPI](https://pypi.org/project/crimson/).
