### ISSUE TITLE
Click dependency on click<8.0 and >=7.0 is a problem

### ISSUE THREAD

**Issue by myourshaw** [bow/crimson#17]
There is a problem installing crimson and other pip modules due to crimson's strict requirement for click<8.0 and >=7.0

ERROR: Cannot install -r requirements.txt (line 11), -r requirements.txt (line 12) and Click because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested Click
    black 22.1.0 depends on click>=8.0.0
    crimson 1.0.0 depends on click<8.0 and >=7.0

**Comment by bow** [comment]
@myourshaw Thanks for reporting this. I just updated both Click and Black's version dependencies in 572c97b ~ they should now both be compatible.
