### ISSUE TITLE
New release is needed to fix PyYAML 5 breaking

### ISSUE THREAD

**Issue by slazicoicr** [bow/crimson#19]
The current release 1.1 still depends on PyYAML 5, which breaks our build and won't be fixed. https://github.com/yaml/pyyaml/pull/726

Since the 1.1 release, PyYAML dependency has build bumped to PyYAML 6. A 1.2 release to PyPi is needed.

**Comment by bow** [comment]
Hey @slazicoicr 

PyYAML (along with other dependencies' versions) have been updated in version 1.1.1, [just recently pushed to PyPI](https://pypi.org/project/crimson/).

Thanks for bringing this up ~ I am marking this issue as resolved.
