### ISSUE TITLE
Fastqc without to extract zip file

### ISSUE THREAD

**Issue by mictadlo** [bow/crimson#2]
Hi,
Could you please add support to read `fastqc.zip` files in order to prevent to extract the archive?

I failed to run the below command:

```
find `pwd`/*_fastqc.zip -type f | parallel -j 3 unzip -c {} {}/fastqc_data.txt | crimson fastqc {} {}.json
```

Thank you in advance.

Mic

**Comment by bow** [comment]
Hi @mictadlo,

Thanks for reporting the issue. Opening from FastQC zip files are not yet supported, but I don't imagine it to be difficult to add. I'll take a look.

**Comment by bow** [comment]
Added in fa0942a.

**Comment by mictadlo** [comment]
Thank you, it works.
