### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by johanneskoester** [bow/crimson#5]
Hi @bow!
Can we get a new release? I am eagerly waiting for the ability to directly take fastqc zip output.

**Comment by bow** [comment]
Hey @johanneskoester,

Wheel and source distribution for latest release (0.4.0) should already be installable from [PyPI](https://pypi.org/project/Crimson/0.4.0/#files) now :).

I'm closing this issue. As always, feel free to let me know if you stumble on any unexpected issues.
