### ISSUE TITLE
Add support for star-fusion 1.7.0

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [bow/crimson#8]
The output format for star-fusion 1.7.0 is not recognized by crimson. The latest version of the output file has some additional columns, and some column names have been changed.

**Comment by bow** [comment]
@Redmar-van-den-Berg , sorry I have missed this for so long :/ ~ I've been off GitHub the past few weeks.

Anyway, do you have an example output for the new version which can be added to the test cases?

**Comment by Redmar-van-den-Berg** [comment]
@bow No problem, I mainly added this issue for myself to work on, but I've been working on another project for the last few weeks. Hopefully I can get to it soon.

On a related note, what do you want to do when a tool changes it's output format?

1. Store the value under the original column header
2. Store the value under the new column header
3. Store the value under the new column header, and also add it under the original column header for backwards compatibility

Introducing duplicate data fields in the output is not nice, but otherwise the client code has to deal with the different column names when a tool is updated. 

I think option 1 would be a bad idea, since then column names from crimson do not match what the users see in their output files.

**Comment by bow** [comment]
> No problem, I mainly added this issue for myself to work on, but I've been working on another project for the last few weeks. Hopefully I can get to it soon.

You can assign yourself to this issue if you'd like to work on it :).

> On a related note, what do you want to do when a tool changes it's output format?

I am of the opinion that we should not try to mix two, possibly incompatible, formats. We should probably treat new versions of the same tool as a new format, don't you think? This is mainly an interface, and the underlying parser may well share a large chunk of the code still.

So for example, let's say STAR-Fusion introduces a new format from version 1.7.0 onwards. What do you think about exposing these three subcommands?

````
# Points to the latest supported version, 1.7.0 in this case.
$ crimson star-fusion
# Points to the corresponding versions
$ crimson star-fusion/0.6.0
$ crimson star-fusion/1.7.0
````

(These are not exactly the correct version numbers, as0.6.0 was the version we Crimson was first written, earlier versions may have the same output format.)

This would give more freedom with regards to the output JSON format as well, and still allow much of the possibly-similar parsing code to be shared internally.

**Comment by bow** [comment]
Closing this issue since #8 has been merged.
